/* eslint-disable */
/* prettier-ignore */
/* oxlint-disable */
/* oxfmt-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const LoadingPlugin: typeof import('tdesign-mobile-vue').LoadingPlugin
  const computed: typeof import('vue').computed
  const myDialog: typeof import('@utils/myPlugin.ts').myDialog
  const myError: typeof import('@utils/myPlugin.ts').myError
  const myLoading: typeof import('@utils/myPlugin.ts').myLoading
  const myMessage: typeof import('@utils/myPlugin.ts').myMessage
  const myWait: typeof import('@utils/myPlugin.ts').myWait
  const nextTick: typeof import('vue').nextTick
  const onMounted: typeof import('vue').onMounted
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const shallowRef: typeof import('vue').shallowRef
  const supportsWasmPthreads: typeof import('./composables/useOpenCV').supportsWasmPthreads
  const supportsWasmSimd: typeof import('./composables/useOpenCV').supportsWasmSimd
  const useData: typeof import('vitepress').useData
  const useLang: typeof import('./composables/useLang').useLang
  const useOpenCV: typeof import('./composables/useOpenCV').useOpenCV
  const useTFjs: typeof import('./composables/useTFjs').useTFjs
  const useTemplateRef: typeof import('vue').useTemplateRef
  const watch: typeof import('vue').watch
  const withBase: typeof import('vitepress').withBase
}
// for type re-export
declare global {
  // @ts-ignore
  export type { OpenCVStatus, OpenCVProfile, OpenCVVariant } from './composables/useOpenCV'
  import('./composables/useOpenCV')
  // @ts-ignore
  export type { TfjsBackend, TfjsStatus } from './composables/useTFjs'
  import('./composables/useTFjs')
}
