/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MyButton: typeof import('./components/MyButton.vue')['default']
    MyChart: typeof import('./components/MyChart.vue')['default']
    MyRadio: typeof import('./components/MyRadio.vue')['default']
    MyTable: typeof import('./components/MyTable.vue')['default']
    MyTest: typeof import('./index/test/MyTest.vue')['default']
    SucroseHydrolysis: typeof import('./index/test/SucroseHydrolysis.vue')['default']
    SucroseHydrolysisChart: typeof import('./index/test/SucroseHydrolysisChart.vue')['default']
    TButton: typeof import('tdesign-mobile-vue')['Button']
    TConfigProvider: typeof import('tdesign-mobile-vue')['ConfigProvider']
    TDrawer: typeof import('tdesign-mobile-vue')['Drawer']
    TInput: typeof import('tdesign-mobile-vue')['Input']
  }
}
