/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AndorAscsToXlsx: typeof import('./index/chemometrics/andor-raman/AndorAscsToXlsx.vue')['default']
    ContactAngle: typeof import('./index/experiment/contact-angle/drop-pic-process/ContactAngle.vue')['default']
    ContactAngleMulti: typeof import('./index/experiment/contact-angle/drop-pic-process/ContactAngleMulti.vue')['default']
    copy: typeof import('./components/MyButton copy.vue')['default']
    MyBadge: typeof import('./components/MyBadge.vue')['default']
    MyButton: typeof import('./components/MyButton.vue')['default']
    MyDownload: typeof import('./components/MyDownload.vue')['default']
    MyDownloadButton: typeof import('./components/MyDownloadButton.vue')['default']
    MyDrawer: typeof import('./components/MyDrawer.vue')['default']
    MyFeatures: typeof import('./components/MyFeatures.vue')['default']
    MyNoticeBar: typeof import('./components/MyNoticeBar.vue')['default']
    MyPicHead: typeof import('./components/MyPicHead.vue')['default']
    MyRadio: typeof import('./components/MyRadio.vue')['default']
    MySlider: typeof import('./components/MySlider.vue')['default']
    MySymbolLineChart: typeof import('./components/MySymbolLineChart.vue')['default']
    MyTable: typeof import('./components/MyTable.vue')['default']
    MyTeamMembers: typeof import('./components/MyTeamMembers.vue')['default']
    MyUpload: typeof import('./components/MyUpload.vue')['default']
    OutlineColorimetric: typeof import('./index/experiment/outline-colorimetric/OutlineColorimetric.vue')['default']
    SucroseHydrolysis: typeof import('./index/experiment/sucrose-hydrolysis/SucroseHydrolysis.vue')['default']
    TButton: typeof import('tdesign-vue-next')['Button']
    TConfigProvider: typeof import('tdesign-vue-next')['ConfigProvider']
    TDivider: typeof import('tdesign-vue-next')['Divider']
    TDrawer: typeof import('tdesign-vue-next')['Drawer']
    Test: typeof import('./index/test/Test.vue')['default']
    TInput: typeof import('tdesign-vue-next')['Input']
    TPagination: typeof import('tdesign-vue-next')['Pagination']
    TRadioButton: typeof import('tdesign-vue-next')['RadioButton']
    TRadioGroup: typeof import('tdesign-vue-next')['RadioGroup']
    TSlider: typeof import('tdesign-vue-next')['Slider']
    TUpload: typeof import('tdesign-vue-next')['Upload']
    VerticalCalibration: typeof import('./index/experiment/contact-angle/vertical-calibration/VerticalCalibration.vue')['default']
  }
}
