/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AndorAscsToXlsx: typeof import('./index/chemometrics/andor-raman/AndorAscsToXlsx.vue')['default']
    ContactAngle: typeof import('./index/experiment/contact-angle/ContactAngle.vue')['default']
    ContactAngleMulti: typeof import('./index/experiment/contact-angle/ContactAngleMulti.vue')['default']
    MyAlert: typeof import('./components/MyAlert.vue')['default']
    MyButton: typeof import('./components/MyButton.vue')['default']
    MyDrawer: typeof import('./components/MyDrawer.vue')['default']
    MyRadio: typeof import('./components/MyRadio.vue')['default']
    MySlider: typeof import('./components/MySlider.vue')['default']
    MySymbolLineChart: typeof import('./components/MySymbolLineChart.vue')['default']
    MyTable: typeof import('./components/MyTable.vue')['default']
    MyTTable: typeof import('./components/MyTTable.vue')['default']
    MyUpload: typeof import('./components/MyUpload.vue')['default']
    OutlineColorimetric: typeof import('./index/experiment/outline-colorimetric/OutlineColorimetric.vue')['default']
    SucroseHydrolysis: typeof import('./index/experiment/sucrose-hydrolysis/SucroseHydrolysis.vue')['default']
    TButton: typeof import('tdesign-mobile-vue')['Button']
    TConfigProvider: typeof import('tdesign-mobile-vue')['ConfigProvider']
    TDrawer: typeof import('tdesign-mobile-vue')['Drawer']
    Test: typeof import('./index/test/Test.vue')['default']
    TInput: typeof import('tdesign-mobile-vue')['Input']
    TNoticeBar: typeof import('tdesign-mobile-vue')['NoticeBar']
    TSlider: typeof import('tdesign-mobile-vue')['Slider']
    TTable: typeof import('tdesign-mobile-vue')['Table']
    TUpload: typeof import('tdesign-mobile-vue')['Upload']
    VerticalCalibration: typeof import('./index/experiment/contact-angle/VerticalCalibration.vue')['default']
  }
}
